apiVersion: v1
kind: Service
metadata:
  name: containerlease
  labels:
    app: containerlease
spec:
  type: ClusterIP
  selector:
    app: containerlease
  ports:
    - name: http
      port: 80
      targetPort: 8080
